package com.example.pagination_new.domain.classesss.film

//import com.example.pagination_new.domain.classes.description.Country
//import com.example.pagination_new.domain.classes.description.Genre
//import com.example.pagination_new.domain.classes.description.Poster
//import com.example.pagination_new.domain.classes.description.Rating

data class Description(
    val ageRating: Int?,
    val alternativeName: String,
    var favorite: Boolean = false,
//    val audience: List<Audience>,
//    val backdrop: Backdrop,
//    val budget: Budget,
    val countries: List<Country>,
//    val deletedAt: Any,
    val description: String,
//    val distributors: Distributors,
    val enName: Any,
//    val externalId: ExternalId,
    val facts: Any,
//    val fees: Fees,
    val genres: List<Genre>,
    val id: Int,
//    val images: Images,
//    val isSeries: Boolean,
//    val isTmdbChecked: Boolean,
//    val keywordsParsed: Boolean,
//    val lists: List<Any?>,
//    val logo: Logo,
//    val movieLength: Int,
    val name: String?,
//    val names: List<Name>,
//    val networks: Any,
    val persons: List<Person>?,
    val poster: Poster?,
//    val premiere: Premiere,
//    val productionCompanies: List<ProductionCompany>,
    val rating: Rating,
//    val ratingMpaa: String,
//    val seasonsInfo: List<Any?>,
//    val sequelsAndPrequels: List<SequelsAndPrequel>,
//    val seriesLength: Any,
//    val shortDescription: Any,
//    val similarMovies: List<SimilarMovy>,
//    val slogan: String,
//    val spokenLanguages: List<SpokenLanguage>,
//    val status: Any,
//    val studioParsed: Boolean,
//    val technology: Technology,
//    val ticketsOnSale: Boolean,
//    val top10: Any,
//    val top250: Any,
//    val totalSeriesLength: Any,
//    val type: String,
//    val typeNumber: Int,
//    val updatedAt: String,
//    val userRatingsParsed: Boolean,
//    val videos: Videos,
//    val votes: Votes,
//    val watchability: Watchability,
    val year: Int?
)